----- CREATES -----

-- Creació de la taula Propietaris
CREATE TABLE Propietaris (
    propietari_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR2(50) NOT NULL,
    cognoms VARCHAR2(50) NOT NULL,
    telefon VARCHAR2(20),
    email VARCHAR2(50),
    PRIMARY KEY (propietari_id)
);

-- Creació de la taula Bicicletes
CREATE TABLE Bicicletes (
    bici_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    marca VARCHAR2(50) NOT NULL,
    model VARCHAR2(50) NOT NULL,
    any_fabricacio NUMBER(4) NOT NULL,
    pes NUMBER(5, 2) NOT NULL,
    tipus VARCHAR2(10) CHECK (tipus IN ('MTB', 'CARRETERA', 'GRAVEL', 'EBIKE')) NOT NULL,
    carboni VARCHAR2(3) CHECK (carboni IN ('SI', 'NO')) NOT NULL,
    propietari_id NUMBER,
    PRIMARY KEY (bici_id),
    FOREIGN KEY (propietari_id) REFERENCES Propietaris(propietari_id) ON DELETE SET NULL
);

-- Creació de la taula Revisions
CREATE TABLE Revisions (
    revisio_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    bici_id NUMBER NOT NULL,
    data DATE NOT NULL,
    descripcio VARCHAR2(255),
    preu NUMBER(5, 2) NOT NULL,
    PRIMARY KEY (revisio_id),
    FOREIGN KEY (bici_id) REFERENCES Bicicletes(bici_id) ON DELETE CASCADE
);

-- Commit per assegurar que els canvis es guarden
COMMIT;

----- DROPS -----

-- Eliminació de la taula Revisions
DROP TABLE Revisions CASCADE CONSTRAINTS;

-- Eliminació de la taula Bicicletes
DROP TABLE Bicicletes CASCADE CONSTRAINTS;

-- Eliminació de la taula Propietaris
DROP TABLE Propietaris CASCADE CONSTRAINTS;

-- Commit per assegurar que els canvis es guarden
COMMIT;

